version: '3.8'

services:
  frontend:
    image: rontti
    ports:
      - 5000:5000
    container_name: rontti-2_8

  backend:
    image: bakki
    ports:
    - 8080:8080
    container_name: bakki-2_8
    environment:
      REDIS_HOST: redis-2_8
      POSTGRES_HOST: database-2_8
      POSTGRES_PORT: 5432
      REQUEST_ORIGIN: http://localhost

  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: redis-2_8

  database:
    image: postgres
    ports:
      - 5432
    container_name: database-2_8
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: database
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

volumes:
  database:
  files:
