name: Release NodeJS app

on:
  push:
    branches:
      - master

jobs:
  login:
    runs-on: ubuntu-latest

    steps:
      - 
        name: Login to Docker Hub2
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd part3/ex01
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest
